name:                Mountain
version:             0.1.0.0
github:              "pmukundan/Mountain"
license:             BSD3
author:              "Priam Mukundan"
maintainer:          "mpriam@gmail.com"
copyright:           "2021 Priam Mukundan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Mountain#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- hspec-megaparsec
- hspec-discover
- hspec-core
- QuickCheck
- algebraic-graphs
- containers
- random
- language-python
- directory
- megaparsec
- text
- parser-combinators
- filepath
- array
- mtl
- uuid
- bytestring
- cryptonite
- memory
- split

library:
  source-dirs: src

executables:
  mountain:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Mountain
    when:        
    - condition: false        
      other-modules: Paths_Mountain

tests:
    spec:
      defaults: hspec/hspec@master
      dependencies:
      - Mountain
